"""Изменены модели для мероприятий

Revision ID: 00aecee0dcdc
Revises: 16f98af51043
Create Date: 2025-10-08 15:00:54.218502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00aecee0dcdc'
down_revision: Union[str, Sequence[str], None] = '16f98af51043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('event_types', sa.Column('leader_id', sa.Integer(), nullable=True))
    op.add_column('event_types', sa.Column('min_stages_for_completion', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('event_types_leader_uid_fkey'), 'event_types', type_='foreignkey')
    op.create_foreign_key(None, 'event_types', 'users', ['leader_id'], ['id'])
    op.drop_column('event_types', 'leader_uid')
    op.add_column('events', sa.Column('description', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_events_description'), 'events', ['description'], unique=False)
    op.add_column('possible_results', sa.Column('points_for_done', sa.Integer(), nullable=True))
    op.add_column('stages', sa.Column('stage_order', sa.Integer(), nullable=True))
    op.add_column('stages', sa.Column('min_score_for_finished', sa.Integer(), nullable=True))
    op.drop_column('stages', 'score_for_finish')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('score_for_finish', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stages', 'min_score_for_finished')
    op.drop_column('stages', 'stage_order')
    op.drop_column('possible_results', 'points_for_done')
    op.drop_index(op.f('ix_events_description'), table_name='events')
    op.drop_column('events', 'description')
    op.add_column('event_types', sa.Column('leader_uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_types', type_='foreignkey')
    op.create_foreign_key(op.f('event_types_leader_uid_fkey'), 'event_types', 'users', ['leader_uid'], ['id'])
    op.drop_column('event_types', 'min_stages_for_completion')
    op.drop_column('event_types', 'leader_id')
    op.drop_column('event_types', 'description')
    # ### end Alembic commands ###
