"""add_is_archive_for_EventType

Revision ID: 115b7919b24e
Revises: 71b2e13b634c
Create Date: 2026-02-16 11:51:49.117649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115b7919b24e'
down_revision: Union[str, Sequence[str], None] = '71b2e13b634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_types', 'is_archived')
    # ### end Alembic commands ###
