"""Fix achievement student relationship

Revision ID: 16f98af51043
Revises: 7c25c945700a
Create Date: 2025-10-08 01:46:41.820451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f98af51043'
down_revision: Union[str, Sequence[str], None] = '7c25c945700a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('student_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_student_achievements_student_external_id'), table_name='student_achievements')
    op.create_foreign_key(None, 'student_achievements', 'users', ['student_id'], ['id'])
    op.drop_column('student_achievements', 'student_external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('student_external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_index(op.f('ix_student_achievements_student_external_id'), 'student_achievements', ['student_external_id'], unique=False)
    op.drop_column('student_achievements', 'student_id')
    # ### end Alembic commands ###
