"""Каскадное удаление

Revision ID: 6c7dc18cb0e3
Revises: ecd95ada7415
Create Date: 2025-10-11 19:03:51.970024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7dc18cb0e3'
down_revision: Union[str, Sequence[str], None] = 'ecd95ada7415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
