"""add_event_importance

Revision ID: 71b2e13b634c
Revises: fcf114dd8846
Create Date: 2026-01-22 09:24:38.217368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b2e13b634c'
down_revision: Union[str, Sequence[str], None] = 'fcf114dd8846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('p_office_event_association', sa.Column('is_important', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('p_office_event_association', 'is_important')
    # ### end Alembic commands ###
