"""add_new_field_for_user

Revision ID: 7c25c945700a
Revises: 3c7adc4bf334
Create Date: 2025-10-07 21:09:37.109415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c25c945700a'
down_revision: Union[str, Sequence[str], None] = '3c7adc4bf334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requires_password', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('archived', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('group_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('groups_leader', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'groups_leader')
    op.drop_column('users', 'group_name')
    op.drop_column('users', 'archived')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'requires_password')
    # ### end Alembic commands ###
