"""Каскадное удаление1

Revision ID: fcf114dd8846
Revises: 6c7dc18cb0e3
Create Date: 2025-10-11 19:05:23.180526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf114dd8846'
down_revision: Union[str, Sequence[str], None] = '6c7dc18cb0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('p_office_event_association_event_id_fkey'), 'p_office_event_association', type_='foreignkey')
    op.drop_constraint(op.f('p_office_event_association_p_office_id_fkey'), 'p_office_event_association', type_='foreignkey')
    op.create_foreign_key(None, 'p_office_event_association', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'p_office_event_association', 'project_offices', ['p_office_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'p_office_event_association', type_='foreignkey')
    op.drop_constraint(None, 'p_office_event_association', type_='foreignkey')
    op.create_foreign_key(op.f('p_office_event_association_p_office_id_fkey'), 'p_office_event_association', 'project_offices', ['p_office_id'], ['id'])
    op.create_foreign_key(op.f('p_office_event_association_event_id_fkey'), 'p_office_event_association', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
